import React from 'react';
import Cta from '@/components/Cta';
import Cars from '@/components/Cars';
import Choose from '@/components/Choose';
import Faq from '@/components/Faq';
import Features from '@/components/Features';
import Hero from '@/components/Hero';
import Services from '@/components/Services';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Home = () => {
  return (
    <div>
      <Hero />
      <Features />
      <Services />
      <Choose />
      <Cars />
      <Faq />
      <Cta />
    </div>
  );
};

export default Home;
