import React from 'react';
import Cta from '@/components/Cta';
import Cars from '@/components/Cars';
import Choose from '@/components/Choose';
import Features from '@/components/Features';
import Hero from '@/components/HomeHero';
import ServiceSection from '@/components/ServiceSection';
import AccordionItem from '@/components/AccordionItem';
import Heading from '@/components/utilities/Heading';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


const accordionItems = [
  {
    title: "What is Comprehensive Vehicle Maintenance?",
    content: "Comprehensive Vehicle Maintenance includes a thorough inspection of your vehicle's engine, spark plug replacement, and interior cleaning to ensure your car runs smoothly and stays clean."
  },
  {
    title: "Why is Engine Oil Change necessary?",
    content: "Engine Oil Change involves replacing the old oil with fresh oil, which is crucial for your engine's health. It helps lubricate engine parts, reduce friction, and maintain optimal performance."
  },
  {
    title: "What does the Tire Care Service include?",
    content: "The Tire Care Service covers tire inflation, tire tread repair, and the installation of new tires when needed. It ensures your tires are safe and in good condition for the road."
  },
];


const Home = () => {
  return (
    <div>
      <Hero />
      <Features />
      <ServiceSection />
      <Choose />
      {/* <Cars /> */}
    <div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
      <Heading headTitle="Frequently Asked Questions" />
      <div class="max-w-xl sm:mx-auto lg:max-w-2xl">
        <div class="space-y-4">
          {accordionItems.map((item, index) => (
          <AccordionItem key={index} title={item.title}>
            {item.content}
          </AccordionItem>
          ))}
        </div>
      </div>
      </div>
      <Cta />
    </div>
  );
};

export default Home;
